# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=20)),
                ('duties', models.CharField(max_length=500)),
                ('requirements', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=10)),
                ('post_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxistation.Worker'),
        ),
    ]
